### ISSUE TITLE
TAG is hardcoded 16 digits and the xid producing 40 digits

### ISSUE THREAD

**Issue by rbucker** [BrianLeishman/go-imap#10]
TAG is hardcoded 16 digits and the xid producing 40 digits.

in d.Exec().... there is some code hardcoded to 16 and 17 digits... it's not exiting the loop.

**Comment by emilhem** [comment]
Isn't this closed by #11 ?

**Comment by emilhem** [comment]
Aah, @BrianLeishman will you tag a new release with the fix in #11 ?
