### ISSUE TITLE
the URL for spew is generating a 404

### ISSUE THREAD

**Issue by rbucker** [BrianLeishman/go-imap#7]
https://github.com/BrianLeishman/go-imap/blob/356e9ab3bc77b5af0c414d53b4153e69cd0c44cf/main.go#L18

spew needs to be removed or replaced. Don't even know what it does.

**Comment by BrianLeishman** [comment]
fixed with https://github.com/BrianLeishman/go-imap/commit/629c09772e1d052093b936f0a7a341d089ee8456

`spew` is the library I use for deep variable logging
