### ISSUE TITLE
Error on GetEmails

### ISSUE THREAD

**Issue by lilithxxx** [BrianLeishman/go-imap#8]
On `GetEmails` I get the following error:
```
parsing time " 8-Sep-2022 14:27:02 +0200" as "02-Jan-2006 15:04:05 -0700": cannot parse " 8-Sep-2022 14:27:02 +0200" as "02"
```

I think it may be due to the number of digits in the day field of time.

**Comment by BrianLeishman** [comment]
fixed with https://github.com/BrianLeishman/go-imap/commit/2a010655c50a50969b611054dff420d889e3d283

**Comment by lilithxxx** [comment]
Thanks but now the `imap.New` function keeps on running without making a connection. Though the logs read: `OK User logged in`.
